-- 0004_chart_of_accounts.sql
-- Chart of Accounts for AQUAHARMONI SDN. BHD. (Kaki Harmoni).
-- Standalone reference chart (no general ledger yet): accounts are browsable,
-- editable, importable/exportable. Per-account balances await a future posting
-- layer. Header accounts are non-postable; transactions may only ever post to
-- active leaf accounts once a ledger exists.
-- Generated from AquaHarmoni_Chart_of_Accounts_Claude_Code_Spec.md (184 accounts).

create table if not exists accounts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid,
  code text not null unique,
  name text not null,
  account_type text not null check (account_type in (
    'header','asset','contra_asset','liability','equity',
    'revenue','contra_revenue','expense','other_income'
  )),
  normal_balance text check (normal_balance in ('debit','credit') or normal_balance is null),
  parent_code text references accounts(code) deferrable initially deferred,
  description text,
  is_postable boolean not null default true,
  is_active boolean not null default true,
  system_locked boolean not null default false,
  statement_group text not null check (statement_group in ('balance_sheet','profit_loss','control')),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists accounts_name_per_parent
  on accounts (coalesce(parent_code, ''), name);
create index if not exists accounts_code_idx on accounts (code);
create index if not exists accounts_parent_idx on accounts (parent_code);
create index if not exists accounts_type_idx on accounts (account_type);
create index if not exists accounts_active_idx on accounts (is_active);
create index if not exists accounts_stmt_idx on accounts (statement_group);

alter table accounts enable row level security;
drop policy if exists "accounts_v1_read" on accounts;
create policy "accounts_v1_read" on accounts for select using (true);
drop policy if exists "accounts_v1_write" on accounts;
create policy "accounts_v1_write" on accounts for all using (true) with check (true);

-- Audit log: creation, edits, (de)activation, blocked deletions. No user
-- attribution yet (app is demo-first, pre-auth).
create table if not exists account_audit (
  id uuid primary key default gen_random_uuid(),
  account_id uuid,
  account_code text,
  action text not null,
  detail jsonb,
  created_at timestamptz not null default now()
);
alter table account_audit enable row level security;
drop policy if exists "account_audit_v1_read" on account_audit;
create policy "account_audit_v1_read" on account_audit for select using (true);
drop policy if exists "account_audit_v1_write" on account_audit;
create policy "account_audit_v1_write" on account_audit for all using (true) with check (true);

-- Seed accounts. Re-runnable: existing codes are left untouched.
insert into accounts
  (code, name, account_type, normal_balance, parent_code, description,
   is_postable, is_active, system_locked, statement_group, sort_order)
values
  ('1000', 'Assets', 'header', null, null, null, false, true, true, 'balance_sheet', 1000),
  ('1100', 'Cash and Bank', 'header', null, '1000', null, false, true, false, 'balance_sheet', 1100),
  ('1110', 'Cash on Hand', 'asset', 'debit', '1100', 'Cash physically held at the outlet.', true, true, false, 'balance_sheet', 1110),
  ('1120', 'Petty Cash', 'asset', 'debit', '1100', 'Small cash float for minor purchases.', true, true, false, 'balance_sheet', 1120),
  ('1130', 'Maybank Current Account', 'asset', 'debit', '1100', 'Primary company operating bank account.', true, true, false, 'balance_sheet', 1130),
  ('1140', 'Payment Gateway Clearing', 'asset', 'debit', '1100', 'Temporary clearing for card, FPX and online payments.', true, true, false, 'balance_sheet', 1140),
  ('1150', 'E-Wallet Receivable', 'asset', 'debit', '1100', 'Amounts due from e-wallet providers.', true, true, false, 'balance_sheet', 1150),
  ('1160', 'Merchant Receivable', 'asset', 'debit', '1100', 'Amounts due from card or payment processors.', true, true, false, 'balance_sheet', 1160),
  ('1170', 'Accounts Receivable', 'asset', 'debit', '1100', 'Amounts owed by customers or corporate clients.', true, true, false, 'balance_sheet', 1170),
  ('1180', 'Other Receivables', 'asset', 'debit', '1100', 'Other short-term receivables.', true, true, false, 'balance_sheet', 1180),
  ('1200', 'Inventory', 'header', null, '1000', null, false, true, false, 'balance_sheet', 1200),
  ('1210', 'Coffee Beans Inventory', 'asset', 'debit', '1200', 'Unused coffee beans held for sale.', true, true, false, 'balance_sheet', 1210),
  ('1220', 'Tea and Beverage Inventory', 'asset', 'debit', '1200', 'Tea, powders, syrups and beverage ingredients.', true, true, false, 'balance_sheet', 1220),
  ('1230', 'Milk and Chilled Ingredients Inventory', 'asset', 'debit', '1200', 'Milk and other chilled café inputs.', true, true, false, 'balance_sheet', 1230),
  ('1240', 'Food Inventory', 'asset', 'debit', '1200', 'Buns, cakes, kuih and food held for resale.', true, true, false, 'balance_sheet', 1240),
  ('1250', 'Essential Oils Inventory', 'asset', 'debit', '1200', 'Essential oils held for service use or resale.', true, true, false, 'balance_sheet', 1250),
  ('1260', 'Retail Merchandise Inventory', 'asset', 'debit', '1200', 'Merchandise and gift items held for resale.', true, true, false, 'balance_sheet', 1260),
  ('1270', 'Packaging Inventory', 'asset', 'debit', '1200', 'Cups, lids, bags and takeaway packaging.', true, true, false, 'balance_sheet', 1270),
  ('1280', 'Operating Consumables Inventory', 'asset', 'debit', '1200', 'Material consumables held for future use.', true, true, false, 'balance_sheet', 1280),
  ('1300', 'Prepayments and Deposits', 'header', null, '1000', null, false, true, false, 'balance_sheet', 1300),
  ('1310', 'Prepaid Rent', 'asset', 'debit', '1300', 'Rent paid for future accounting periods.', true, true, false, 'balance_sheet', 1310),
  ('1320', 'Prepaid Insurance', 'asset', 'debit', '1300', 'Insurance premiums relating to future periods.', true, true, false, 'balance_sheet', 1320),
  ('1330', 'Prepaid Licences', 'asset', 'debit', '1300', 'Business licences paid in advance.', true, true, false, 'balance_sheet', 1330),
  ('1340', 'Prepaid Domain and Hosting', 'asset', 'debit', '1300', 'Multi-period domain, hosting or SSL payments when material.', true, true, false, 'balance_sheet', 1340),
  ('1350', 'Prepaid Software Subscriptions', 'asset', 'debit', '1300', 'Multi-period software subscriptions when material.', true, true, false, 'balance_sheet', 1350),
  ('1360', 'Rental and Utility Deposits', 'asset', 'debit', '1300', 'Refundable deposits paid to landlords or utility providers.', true, true, false, 'balance_sheet', 1360),
  ('1370', 'Supplier Deposits', 'asset', 'debit', '1300', 'Refundable or advance deposits paid to suppliers.', true, true, false, 'balance_sheet', 1370),
  ('1500', 'Property, Plant and Equipment', 'header', null, '1000', null, false, true, false, 'balance_sheet', 1500),
  ('1510', 'Furniture and Fittings', 'asset', 'debit', '1500', 'Tables, chairs, counters, shelving and fittings.', true, true, false, 'balance_sheet', 1510),
  ('1520', 'Wellness Equipment', 'asset', 'debit', '1500', 'Wellness machines, foot tubs and related equipment.', true, true, false, 'balance_sheet', 1520),
  ('1530', 'Café Equipment', 'asset', 'debit', '1500', 'Coffee machine, toaster, refrigerator and café equipment.', true, true, false, 'balance_sheet', 1530),
  ('1540', 'Water System Equipment', 'asset', 'debit', '1500', 'Water filters, heaters, pumps and tanks.', true, true, false, 'balance_sheet', 1540),
  ('1550', 'Air Conditioning and Ventilation', 'asset', 'debit', '1500', 'Air conditioners, wall fans and ventilation equipment.', true, true, false, 'balance_sheet', 1550),
  ('1560', 'Computer and Office Equipment', 'asset', 'debit', '1500', 'Computers, printers and office hardware.', true, true, false, 'balance_sheet', 1560),
  ('1570', 'POS and Payment Equipment', 'asset', 'debit', '1500', 'POS terminals, receipt printers and scanners.', true, true, false, 'balance_sheet', 1570),
  ('1580', 'CCTV and Security Equipment', 'asset', 'debit', '1500', 'CCTV, alarms and related security hardware.', true, true, false, 'balance_sheet', 1580),
  ('1590', 'Renovation and Fit-Out', 'asset', 'debit', '1500', 'Capital renovation and fit-out works.', true, true, false, 'balance_sheet', 1590),
  ('1600', 'Accumulated Depreciation', 'header', null, '1000', null, false, true, false, 'balance_sheet', 1600),
  ('1610', 'Accumulated Depreciation - Furniture and Fittings', 'contra_asset', 'credit', '1600', 'Accumulated depreciation for furniture and fittings.', true, true, false, 'balance_sheet', 1610),
  ('1620', 'Accumulated Depreciation - Wellness Equipment', 'contra_asset', 'credit', '1600', 'Accumulated depreciation for wellness equipment.', true, true, false, 'balance_sheet', 1620),
  ('1630', 'Accumulated Depreciation - Café Equipment', 'contra_asset', 'credit', '1600', 'Accumulated depreciation for café equipment.', true, true, false, 'balance_sheet', 1630),
  ('1640', 'Accumulated Depreciation - Water System Equipment', 'contra_asset', 'credit', '1600', 'Accumulated depreciation for water system equipment.', true, true, false, 'balance_sheet', 1640),
  ('1650', 'Accumulated Depreciation - Air Conditioning', 'contra_asset', 'credit', '1600', 'Accumulated depreciation for air conditioning and ventilation.', true, true, false, 'balance_sheet', 1650),
  ('1660', 'Accumulated Depreciation - Computer and Office Equipment', 'contra_asset', 'credit', '1600', 'Accumulated depreciation for computer and office equipment.', true, true, false, 'balance_sheet', 1660),
  ('1670', 'Accumulated Depreciation - POS and Security Equipment', 'contra_asset', 'credit', '1600', 'Accumulated depreciation for POS and security equipment.', true, true, false, 'balance_sheet', 1670),
  ('1680', 'Accumulated Depreciation - Renovation and Fit-Out', 'contra_asset', 'credit', '1600', 'Accumulated depreciation for renovation and fit-out.', true, true, false, 'balance_sheet', 1680),
  ('2000', 'Liabilities', 'header', null, null, null, false, true, true, 'balance_sheet', 2000),
  ('2100', 'Current Liabilities', 'header', null, '2000', null, false, true, false, 'balance_sheet', 2100),
  ('2110', 'Accounts Payable', 'liability', 'credit', '2100', 'Amounts owed to suppliers.', true, true, false, 'balance_sheet', 2110),
  ('2120', 'Accrued Expenses', 'liability', 'credit', '2100', 'Expenses incurred but not yet paid or invoiced.', true, true, false, 'balance_sheet', 2120),
  ('2130', 'Customer Deposits and Unearned Revenue', 'liability', 'credit', '2100', 'Advance payments, prepaid packages and vouchers not yet redeemed.', true, true, false, 'balance_sheet', 2130),
  ('2140', 'SST Payable', 'liability', 'credit', '2100', 'Sales and service tax payable when applicable.', true, true, false, 'balance_sheet', 2140),
  ('2150', 'EPF Payable', 'liability', 'credit', '2100', 'Employee and employer EPF amounts awaiting remittance.', true, true, false, 'balance_sheet', 2150),
  ('2160', 'SOCSO Payable', 'liability', 'credit', '2100', 'SOCSO contributions awaiting remittance.', true, true, false, 'balance_sheet', 2160),
  ('2170', 'EIS Payable', 'liability', 'credit', '2100', 'EIS contributions awaiting remittance.', true, true, false, 'balance_sheet', 2170),
  ('2180', 'PCB/MTD Payable', 'liability', 'credit', '2100', 'Payroll tax deductions awaiting remittance.', true, true, false, 'balance_sheet', 2180),
  ('2190', 'Other Payables', 'liability', 'credit', '2100', 'Other short-term amounts payable.', true, true, false, 'balance_sheet', 2190),
  ('2200', 'Loans and Financing', 'header', null, '2000', null, false, true, false, 'balance_sheet', 2200),
  ('2210', 'Director Loan - Goh Hian Gek', 'liability', 'credit', '2200', 'Amounts advanced to the company by this director.', true, true, false, 'balance_sheet', 2210),
  ('2220', 'Director Loan - Hew Lee Ling', 'liability', 'credit', '2200', 'Amounts advanced to the company by this director.', true, true, false, 'balance_sheet', 2220),
  ('2230', 'Director Loan - Yap Sau Yong', 'liability', 'credit', '2200', 'Amounts advanced to the company by this director.', true, true, false, 'balance_sheet', 2230),
  ('2240', 'Bank Loan - Current Portion', 'liability', 'credit', '2200', 'Principal due within twelve months.', true, true, false, 'balance_sheet', 2240),
  ('2250', 'Hire Purchase - Current Portion', 'liability', 'credit', '2200', 'Hire purchase principal due within twelve months.', true, true, false, 'balance_sheet', 2250),
  ('2300', 'Non-Current Liabilities', 'header', null, '2000', null, false, true, false, 'balance_sheet', 2300),
  ('2310', 'Bank Loan - Non-Current Portion', 'liability', 'credit', '2300', 'Bank loan principal due after twelve months.', true, true, false, 'balance_sheet', 2310),
  ('2320', 'Hire Purchase - Non-Current Portion', 'liability', 'credit', '2300', 'Hire purchase principal due after twelve months.', true, true, false, 'balance_sheet', 2320),
  ('3000', 'Equity', 'header', null, null, null, false, true, true, 'balance_sheet', 3000),
  ('3100', 'Share Capital', 'equity', 'credit', '3000', 'Issued and paid-up share capital.', true, true, false, 'balance_sheet', 3100),
  ('3200', 'Retained Earnings', 'equity', 'credit', '3000', 'Accumulated prior-year profits or losses.', true, true, false, 'balance_sheet', 3200),
  ('3300', 'Current Year Earnings', 'equity', 'credit', '3000', 'System-controlled current-year profit or loss.', true, true, true, 'balance_sheet', 3300),
  ('3400', 'Dividends Declared', 'equity', 'debit', '3000', 'Dividends declared to shareholders.', true, true, false, 'balance_sheet', 3400),
  ('4000', 'Revenue', 'header', null, null, null, false, true, true, 'profit_loss', 4000),
  ('4100', 'Wellness Revenue', 'header', null, '4000', null, false, true, false, 'profit_loss', 4100),
  ('4110', 'Wellness Session Revenue', 'revenue', 'credit', '4100', 'Standard wellness session sales.', true, true, false, 'profit_loss', 4110),
  ('4120', 'Resident Wellness Revenue', 'revenue', 'credit', '4100', 'Sessions sold at resident pricing.', true, true, false, 'profit_loss', 4120),
  ('4130', 'Early Bird Wellness Revenue', 'revenue', 'credit', '4100', 'Sessions sold at early-bird pricing.', true, true, false, 'profit_loss', 4130),
  ('4140', 'Membership and Package Revenue', 'revenue', 'credit', '4100', 'Revenue recognized as packages are redeemed.', true, true, false, 'profit_loss', 4140),
  ('4150', 'Gift Voucher Revenue', 'revenue', 'credit', '4100', 'Revenue recognized when vouchers are redeemed.', true, true, false, 'profit_loss', 4150),
  ('4200', 'Café Revenue', 'header', null, '4000', null, false, true, false, 'profit_loss', 4200),
  ('4210', 'Coffee Sales', 'revenue', 'credit', '4200', 'Coffee beverage sales.', true, true, false, 'profit_loss', 4210),
  ('4220', 'Tea and Other Beverage Sales', 'revenue', 'credit', '4200', 'Tea, healthy drinks and other beverage sales.', true, true, false, 'profit_loss', 4220),
  ('4230', 'Food and Snack Sales', 'revenue', 'credit', '4200', 'Buns, cakes, kuih and snack sales.', true, true, false, 'profit_loss', 4230),
  ('4300', 'Retail and Other Revenue', 'header', null, '4000', null, false, true, false, 'profit_loss', 4300),
  ('4310', 'Essential Oil Sales', 'revenue', 'credit', '4300', 'Retail sales of essential oils.', true, true, false, 'profit_loss', 4310),
  ('4320', 'Merchandise Sales', 'revenue', 'credit', '4300', 'Retail sales of branded or gift merchandise.', true, true, false, 'profit_loss', 4320),
  ('4330', 'Other Operating Revenue', 'revenue', 'credit', '4300', 'Other income generated from normal operations.', true, true, false, 'profit_loss', 4330),
  ('4900', 'Sales Discounts and Refunds', 'contra_revenue', 'debit', '4000', 'Discounts, refunds and sales returns.', true, true, false, 'profit_loss', 4900),
  ('5000', 'Cost of Sales', 'header', null, null, null, false, true, true, 'profit_loss', 5000),
  ('5100', 'Wellness Cost of Sales', 'header', null, '5000', null, false, true, false, 'profit_loss', 5100),
  ('5110', 'Essential Oils Used in Services', 'expense', 'debit', '5100', 'Essential oils consumed in wellness sessions.', true, true, false, 'profit_loss', 5110),
  ('5120', 'Towels and Laundry - Direct', 'expense', 'debit', '5100', 'Direct laundry and towel costs for sessions.', true, true, false, 'profit_loss', 5120),
  ('5130', 'Wellness Consumables', 'expense', 'debit', '5100', 'Direct consumables used per customer session.', true, true, false, 'profit_loss', 5130),
  ('5200', 'Café Cost of Sales', 'header', null, '5000', null, false, true, false, 'profit_loss', 5200),
  ('5210', 'Coffee Beans Used', 'expense', 'debit', '5200', 'Coffee beans consumed in drinks sold.', true, true, false, 'profit_loss', 5210),
  ('5220', 'Milk and Beverage Ingredients Used', 'expense', 'debit', '5200', 'Milk, tea, syrups and beverage ingredients consumed.', true, true, false, 'profit_loss', 5220),
  ('5230', 'Food and Snack Purchases', 'expense', 'debit', '5200', 'Food purchased for resale.', true, true, false, 'profit_loss', 5230),
  ('5240', 'Takeaway Packaging Used', 'expense', 'debit', '5200', 'Cups, lids, bags and other packaging consumed.', true, true, false, 'profit_loss', 5240),
  ('5300', 'Retail Cost of Sales', 'header', null, '5000', null, false, true, false, 'profit_loss', 5300),
  ('5310', 'Essential Oils Sold - Cost', 'expense', 'debit', '5300', 'Cost of essential oils sold as retail products.', true, true, false, 'profit_loss', 5310),
  ('5320', 'Merchandise Sold - Cost', 'expense', 'debit', '5300', 'Cost of merchandise sold.', true, true, false, 'profit_loss', 5320),
  ('6000', 'Operating Expenses', 'header', null, null, null, false, true, true, 'profit_loss', 6000),
  ('6100', 'Payroll and People', 'header', null, '6000', null, false, true, false, 'profit_loss', 6100),
  ('6110', 'Salaries and Wages', 'expense', 'debit', '6100', 'Employee salaries and wages.', true, true, false, 'profit_loss', 6110),
  ('6120', 'Director Allowances', 'expense', 'debit', '6100', 'Approved director allowances.', true, true, false, 'profit_loss', 6120),
  ('6130', 'Employer EPF', 'expense', 'debit', '6100', 'Employer EPF contributions.', true, true, false, 'profit_loss', 6130),
  ('6140', 'Employer SOCSO', 'expense', 'debit', '6100', 'Employer SOCSO contributions.', true, true, false, 'profit_loss', 6140),
  ('6150', 'Employer EIS', 'expense', 'debit', '6100', 'Employer EIS contributions.', true, true, false, 'profit_loss', 6150),
  ('6160', 'Staff Training', 'expense', 'debit', '6100', 'Training and certification costs.', true, true, false, 'profit_loss', 6160),
  ('6170', 'Staff Welfare', 'expense', 'debit', '6100', 'Meals, welfare and staff benefits.', true, true, false, 'profit_loss', 6170),
  ('6180', 'Uniforms and Protective Items', 'expense', 'debit', '6100', 'Uniforms and work-related protective items.', true, true, false, 'profit_loss', 6180),
  ('6200', 'Premises and Utilities', 'header', null, '6000', null, false, true, false, 'profit_loss', 6200),
  ('6210', 'Rent and Service Charges', 'expense', 'debit', '6200', 'Premises rent and management or service charges.', true, true, false, 'profit_loss', 6210),
  ('6220', 'Electricity', 'expense', 'debit', '6200', 'Electricity usage.', true, true, false, 'profit_loss', 6220),
  ('6230', 'Water and Sewerage', 'expense', 'debit', '6200', 'Water and sewerage charges.', true, true, false, 'profit_loss', 6230),
  ('6240', 'Internet and Telephone', 'expense', 'debit', '6200', 'Internet, mobile and telephone costs.', true, true, false, 'profit_loss', 6240),
  ('6250', 'Cleaning Services', 'expense', 'debit', '6200', 'External or routine cleaning services.', true, true, false, 'profit_loss', 6250),
  ('6260', 'Cleaning Supplies', 'expense', 'debit', '6200', 'Cleaning chemicals and supplies not treated as inventory.', true, true, false, 'profit_loss', 6260),
  ('6270', 'Pest Control', 'expense', 'debit', '6200', 'Pest control services.', true, true, false, 'profit_loss', 6270),
  ('6280', 'Repairs and Maintenance', 'expense', 'debit', '6200', 'Routine repair and maintenance costs.', true, true, false, 'profit_loss', 6280),
  ('6290', 'Waste Disposal', 'expense', 'debit', '6200', 'Waste collection and disposal costs.', true, true, false, 'profit_loss', 6290),
  ('6300', 'Sales and Marketing', 'header', null, '6000', null, false, true, false, 'profit_loss', 6300),
  ('6310', 'Digital Advertising', 'expense', 'debit', '6300', 'Facebook, Instagram, TikTok, RED and Google advertising.', true, true, false, 'profit_loss', 6310),
  ('6320', 'Print Advertising and Flyers', 'expense', 'debit', '6300', 'Flyers, brochures and print advertising.', true, true, false, 'profit_loss', 6320),
  ('6330', 'Photography and Content Production', 'expense', 'debit', '6300', 'Photography, video and content production.', true, true, false, 'profit_loss', 6330),
  ('6340', 'Promotions and Complimentary Sessions', 'expense', 'debit', '6300', 'Promotional giveaways and complimentary services.', true, true, false, 'profit_loss', 6340),
  ('6350', 'Influencer and Partnership Fees', 'expense', 'debit', '6300', 'Influencer, referral and promotional partnership fees.', true, true, false, 'profit_loss', 6350),
  ('6360', 'Signage and Temporary Promotional Materials', 'expense', 'debit', '6300', 'Non-capital signage and temporary promotional materials.', true, true, false, 'profit_loss', 6360),
  ('6400', 'Office and Technology', 'header', null, '6000', null, false, true, false, 'profit_loss', 6400),
  ('6410', 'Office Supplies and Stationery', 'expense', 'debit', '6400', 'General stationery and office supplies.', true, true, false, 'profit_loss', 6410),
  ('6420', 'Printing and Photocopying', 'expense', 'debit', '6400', 'Routine printing and photocopying.', true, true, false, 'profit_loss', 6420),
  ('6430', 'Postage and Courier', 'expense', 'debit', '6400', 'Postal and courier costs.', true, true, false, 'profit_loss', 6430),
  ('6440', 'Software and SaaS Subscriptions', 'expense', 'debit', '6400', 'General software subscriptions.', true, true, false, 'profit_loss', 6440),
  ('6450', 'AI Software Subscriptions', 'expense', 'debit', '6400', 'ChatGPT, Claude and related AI subscriptions.', true, true, false, 'profit_loss', 6450),
  ('6460', 'Productivity and Design Software', 'expense', 'debit', '6400', 'Microsoft 365, Google Workspace, Canva and similar tools.', true, true, false, 'profit_loss', 6460),
  ('6470', 'POS and App Subscription Fees', 'expense', 'debit', '6400', 'Recurring POS and financial app subscription charges.', true, true, false, 'profit_loss', 6470),
  ('6480', 'IT Support and Maintenance', 'expense', 'debit', '6400', 'IT support, repairs and maintenance.', true, true, false, 'profit_loss', 6480),
  ('6500', 'Website and Digital Infrastructure', 'header', null, '6000', null, false, true, false, 'profit_loss', 6500),
  ('6510', 'Domain Registration Fees', 'expense', 'debit', '6500', 'Annual or immaterial domain registration and renewal fees.', true, true, false, 'profit_loss', 6510),
  ('6520', 'Web Hosting and Cloud Services', 'expense', 'debit', '6500', 'Hosting, serverless, database and cloud costs.', true, true, false, 'profit_loss', 6520),
  ('6530', 'Website Maintenance', 'expense', 'debit', '6500', 'Routine website updates and maintenance.', true, true, false, 'profit_loss', 6530),
  ('6540', 'SSL and Security Services', 'expense', 'debit', '6500', 'Paid SSL certificates and website security services.', true, true, false, 'profit_loss', 6540),
  ('6550', 'Minor Website Development', 'expense', 'debit', '6500', 'Minor enhancements that do not meet capitalization criteria.', true, true, false, 'profit_loss', 6550),
  ('6600', 'Professional, Compliance and Administration', 'header', null, '6000', null, false, true, false, 'profit_loss', 6600),
  ('6610', 'Accounting and Bookkeeping Fees', 'expense', 'debit', '6600', 'Accounting and bookkeeping services.', true, true, false, 'profit_loss', 6610),
  ('6620', 'Audit and Assurance Fees', 'expense', 'debit', '6600', 'Audit or assurance services.', true, true, false, 'profit_loss', 6620),
  ('6630', 'Company Secretarial Fees', 'expense', 'debit', '6600', 'Company secretary retainers and filing fees.', true, true, false, 'profit_loss', 6630),
  ('6640', 'Legal Fees', 'expense', 'debit', '6600', 'Legal advice and documentation.', true, true, false, 'profit_loss', 6640),
  ('6650', 'Tax Agent Fees', 'expense', 'debit', '6600', 'Tax compliance and advisory fees.', true, true, false, 'profit_loss', 6650),
  ('6660', 'Business Licence and Permit Fees', 'expense', 'debit', '6600', 'DBKL and other operating licence fees.', true, true, false, 'profit_loss', 6660),
  ('6670', 'Trademark and Intellectual Property Fees', 'expense', 'debit', '6600', 'Trademark searches, filings and related professional fees unless capitalized.', true, true, false, 'profit_loss', 6670),
  ('6680', 'Consultancy Fees', 'expense', 'debit', '6600', 'External consultancy services.', true, true, false, 'profit_loss', 6680),
  ('6690', 'Training and Certification - Business', 'expense', 'debit', '6600', 'Business-level training and certifications.', true, true, false, 'profit_loss', 6690),
  ('6700', 'General and Administrative', 'header', null, '6000', null, false, true, false, 'profit_loss', 6700),
  ('6710', 'Insurance Expense', 'expense', 'debit', '6700', 'Business insurance expense for the period.', true, true, false, 'profit_loss', 6710),
  ('6720', 'Bank Charges', 'expense', 'debit', '6700', 'Bank fees and transaction charges.', true, true, false, 'profit_loss', 6720),
  ('6730', 'Merchant and Payment Gateway Fees', 'expense', 'debit', '6700', 'Card, FPX and e-wallet processing fees.', true, true, false, 'profit_loss', 6730),
  ('6740', 'Travel and Transport', 'expense', 'debit', '6700', 'Business travel, parking, tolls and transport.', true, true, false, 'profit_loss', 6740),
  ('6750', 'Meals and Entertainment', 'expense', 'debit', '6700', 'Business meals and entertainment.', true, true, false, 'profit_loss', 6750),
  ('6760', 'Subscriptions and Memberships', 'expense', 'debit', '6700', 'Trade memberships and non-software subscriptions.', true, true, false, 'profit_loss', 6760),
  ('6770', 'Licence Renewal Penalties and Fines', 'expense', 'debit', '6700', 'Non-deductible fines and penalties; keep separately identifiable.', true, true, false, 'profit_loss', 6770),
  ('6780', 'Donations and Sponsorships', 'expense', 'debit', '6700', 'Donations and sponsorship costs.', true, true, false, 'profit_loss', 6780),
  ('6790', 'Miscellaneous Administrative Expense', 'expense', 'debit', '6700', 'Infrequent, low-value administrative expenses.', true, true, false, 'profit_loss', 6790),
  ('6800', 'Depreciation and Amortisation', 'header', null, '6000', null, false, true, false, 'profit_loss', 6800),
  ('6810', 'Depreciation - Furniture and Fittings', 'expense', 'debit', '6800', 'Periodic depreciation charge.', true, true, false, 'profit_loss', 6810),
  ('6820', 'Depreciation - Wellness Equipment', 'expense', 'debit', '6800', 'Periodic depreciation charge.', true, true, false, 'profit_loss', 6820),
  ('6830', 'Depreciation - Café Equipment', 'expense', 'debit', '6800', 'Periodic depreciation charge.', true, true, false, 'profit_loss', 6830),
  ('6840', 'Depreciation - Water and Air Conditioning Equipment', 'expense', 'debit', '6800', 'Periodic depreciation charge.', true, true, false, 'profit_loss', 6840),
  ('6850', 'Depreciation - Computer, POS and Security Equipment', 'expense', 'debit', '6800', 'Periodic depreciation charge.', true, true, false, 'profit_loss', 6850),
  ('6860', 'Depreciation - Renovation and Fit-Out', 'expense', 'debit', '6800', 'Periodic depreciation charge.', true, true, false, 'profit_loss', 6860),
  ('7000', 'Finance Costs', 'header', null, null, null, false, true, true, 'profit_loss', 7000),
  ('7110', 'Bank Loan Interest', 'expense', 'debit', '7000', 'Interest on bank loans.', true, true, false, 'profit_loss', 7110),
  ('7120', 'Hire Purchase Interest', 'expense', 'debit', '7000', 'Interest portion of hire purchase payments.', true, true, false, 'profit_loss', 7120),
  ('7130', 'Director Loan Interest', 'expense', 'debit', '7000', 'Interest payable on interest-bearing director loans.', true, true, false, 'profit_loss', 7130),
  ('7140', 'Late Payment Charges', 'expense', 'debit', '7000', 'Late payment charges excluding statutory fines.', true, true, false, 'profit_loss', 7140),
  ('8000', 'Other Income', 'header', null, null, null, false, true, true, 'profit_loss', 8000),
  ('8110', 'Bank Interest Income', 'other_income', 'credit', '8000', 'Interest earned on bank balances.', true, true, false, 'profit_loss', 8110),
  ('8120', 'Government Grants', 'other_income', 'credit', '8000', 'Government grants recognized as income.', true, true, false, 'profit_loss', 8120),
  ('8130', 'Insurance Claims Received', 'other_income', 'credit', '8000', 'Insurance proceeds recognized as income.', true, true, false, 'profit_loss', 8130),
  ('8140', 'Gain on Disposal of Assets', 'other_income', 'credit', '8000', 'Gain on disposal of fixed assets.', true, true, false, 'profit_loss', 8140),
  ('8190', 'Other Non-Operating Income', 'other_income', 'credit', '8000', 'Other non-operating income.', true, true, false, 'profit_loss', 8190),
  ('9000', 'System and Control Accounts', 'header', null, null, null, false, true, true, 'control', 9000),
  ('9110', 'Opening Balance Equity', 'equity', 'credit', '9000', 'Temporary migration-only account; lock after setup.', true, true, true, 'control', 9110),
  ('9120', 'Suspense Account', 'asset', 'debit', '9000', 'Temporary unidentified transactions; must be cleared.', true, true, true, 'control', 9120),
  ('9130', 'Rounding Differences', 'expense', 'debit', '9000', 'Small system rounding differences.', true, true, false, 'control', 9130)
on conflict (code) do nothing;
